-- Новая детализация листа 01_02_03 "Цели кредитования".
--
-- Старые агрегированные коды 6.52.1–6.57.3 остаются legacy-рядами.
-- Новая сетка:
--   6.52–6.57   программа
--   .1–.6       цель кредитования (у Семейной ипотеки 6 целей)
--   .1 / .2     количество / объем

INSERT INTO indicators (
    code, name, unit, chart_type, periodicity, period_type,
    is_public, is_calculated, category_id, source_id, sort_order
) VALUES
('6.52.1.1', 'Покупка по ДДУ (количество, Все программы)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 220),
('6.52.1.2', 'Покупка по ДДУ (объем, Все программы)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 221),
('6.52.2.1', 'Покупка по ДКП у застройщика (количество, Все программы)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 222),
('6.52.2.2', 'Покупка по ДКП у застройщика (объем, Все программы)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 223),
('6.52.3.1', 'Индивидуальное жилищное строительство (количество, Все программы)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 224),
('6.52.3.2', 'Индивидуальное жилищное строительство (объем, Все программы)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 225),
('6.52.4.1', 'Готовый индивидуальный жилой дом (количество, Все программы)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 226),
('6.52.4.2', 'Готовый индивидуальный жилой дом (объем, Все программы)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 227),
('6.52.5.1', 'Покупка квартир по ДКП на вторичке (количество, Все программы)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 228),
('6.52.5.2', 'Покупка квартир по ДКП на вторичке (объем, Все программы)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 229),
('6.53.1.1', 'Покупка по ДДУ (количество, Льготная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 230),
('6.53.1.2', 'Покупка по ДДУ (объем, Льготная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 231),
('6.53.2.1', 'Покупка по ДКП у застройщика (количество, Льготная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 232),
('6.53.2.2', 'Покупка по ДКП у застройщика (объем, Льготная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 233),
('6.53.3.1', 'Индивидуальное жилищное строительство (количество, Льготная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 234),
('6.53.3.2', 'Индивидуальное жилищное строительство (объем, Льготная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 235),
('6.53.4.1', 'Готовый индивидуальный жилой дом (количество, Льготная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 236),
('6.53.4.2', 'Готовый индивидуальный жилой дом (объем, Льготная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 237),
('6.53.5.1', 'Покупка квартир по ДКП на вторичке (количество, Льготная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 238),
('6.53.5.2', 'Покупка квартир по ДКП на вторичке (объем, Льготная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 239),
('6.54.1.1', 'Покупка по ДДУ (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 240),
('6.54.1.2', 'Покупка по ДДУ (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 241),
('6.54.2.1', 'Покупка по ДКП у застройщика (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 242),
('6.54.2.2', 'Покупка по ДКП у застройщика (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 243),
('6.54.3.1', 'Индивидуальное жилищное строительство (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 244),
('6.54.3.2', 'Индивидуальное жилищное строительство (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 245),
('6.54.4.1', 'Готовый индивидуальный жилой дом (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 246),
('6.54.4.2', 'Готовый индивидуальный жилой дом (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 247),
('6.54.5.1', 'Покупка квартир по ДКП на вторичке в городах без стройки (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 248),
('6.54.5.2', 'Покупка квартир по ДКП на вторичке в городах без стройки (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 249),
('6.54.6.1', 'Покупка квартир по ДКП на вторичке, прочее (количество, Семейная ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 250),
('6.54.6.2', 'Покупка квартир по ДКП на вторичке, прочее (объем, Семейная ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 251),
('6.55.1.1', 'Покупка по ДДУ (количество, Дальневосточная и арктическая ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 252),
('6.55.1.2', 'Покупка по ДДУ (объем, Дальневосточная и арктическая ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 253),
('6.55.2.1', 'Покупка по ДКП у застройщика (количество, Дальневосточная и арктическая ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 254),
('6.55.2.2', 'Покупка по ДКП у застройщика (объем, Дальневосточная и арктическая ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 255),
('6.55.3.1', 'Индивидуальное жилищное строительство (количество, Дальневосточная и арктическая ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 256),
('6.55.3.2', 'Индивидуальное жилищное строительство (объем, Дальневосточная и арктическая ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 257),
('6.55.4.1', 'Готовый индивидуальный жилой дом (количество, Дальневосточная и арктическая ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 258),
('6.55.4.2', 'Готовый индивидуальный жилой дом (объем, Дальневосточная и арктическая ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 259),
('6.55.5.1', 'Покупка квартир по ДКП на вторичке (количество, Дальневосточная и арктическая ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 260),
('6.55.5.2', 'Покупка квартир по ДКП на вторичке (объем, Дальневосточная и арктическая ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 261),
('6.56.1.1', 'Покупка по ДДУ (количество, IT ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 262),
('6.56.1.2', 'Покупка по ДДУ (объем, IT ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 263),
('6.56.2.1', 'Покупка по ДКП у застройщика (количество, IT ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 264),
('6.56.2.2', 'Покупка по ДКП у застройщика (объем, IT ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 265),
('6.56.3.1', 'Индивидуальное жилищное строительство (количество, IT ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 266),
('6.56.3.2', 'Индивидуальное жилищное строительство (объем, IT ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 267),
('6.56.4.1', 'Готовый индивидуальный жилой дом (количество, IT ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 268),
('6.56.4.2', 'Готовый индивидуальный жилой дом (объем, IT ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 269),
('6.56.5.1', 'Покупка квартир по ДКП на вторичке (количество, IT ипотека)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 270),
('6.56.5.2', 'Покупка квартир по ДКП на вторичке (объем, IT ипотека)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 271),
('6.57.1.1', 'Покупка по ДДУ (количество, Ипотека в отдельных регионах)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 272),
('6.57.1.2', 'Покупка по ДДУ (объем, Ипотека в отдельных регионах)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 273),
('6.57.2.1', 'Покупка по ДКП у застройщика (количество, Ипотека в отдельных регионах)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 274),
('6.57.2.2', 'Покупка по ДКП у застройщика (объем, Ипотека в отдельных регионах)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 275),
('6.57.3.1', 'Индивидуальное жилищное строительство (количество, Ипотека в отдельных регионах)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 276),
('6.57.3.2', 'Индивидуальное жилищное строительство (объем, Ипотека в отдельных регионах)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 277),
('6.57.4.1', 'Готовый индивидуальный жилой дом (количество, Ипотека в отдельных регионах)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 278),
('6.57.4.2', 'Готовый индивидуальный жилой дом (объем, Ипотека в отдельных регионах)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 279),
('6.57.5.1', 'Покупка квартир по ДКП на вторичке (количество, Ипотека в отдельных регионах)', 'шт.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 280),
('6.57.5.2', 'Покупка квартир по ДКП на вторичке (объем, Ипотека в отдельных регионах)', 'млн руб.', 'bar', 'monthly', 'period', false, false, (SELECT id FROM categories WHERE code='mortgage_subsidy'), (SELECT id FROM sources WHERE code='domrf'), 281)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    unit = EXCLUDED.unit,
    chart_type = EXCLUDED.chart_type,
    periodicity = EXCLUDED.periodicity,
    period_type = EXCLUDED.period_type,
    is_public = EXCLUDED.is_public,
    is_calculated = EXCLUDED.is_calculated,
    category_id = EXCLUDED.category_id,
    source_id = EXCLUDED.source_id,
    sort_order = EXCLUDED.sort_order;
